version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fluxa_dev}
      POSTGRES_USER: ${POSTGRES_USER:-fluxa_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fluxa_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fluxa_user} -d ${POSTGRES_DB:-fluxa_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - docker-compose.env

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - DATABASE_URL=${DATABASE_URL:-postgresql://fluxa_user:fluxa_password@postgres:5432/fluxa_dev}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_your_stripe_secret_key_here}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_your_webhook_secret_here}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-703528071436-urk38sfoh9nc7g6b6jrbme715b998inp.apps.googleusercontent.com}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost:3000,http://localhost:5173,http://localhost:4173,http://localhost:8080}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_ENABLE_DEBUG_MODE=${VITE_ENABLE_DEBUG_MODE:-true}
      - VITE_APP_TITLE=${VITE_APP_TITLE:-Fluxa (Dev)}
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: 